2015-12-03 18:29:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "-"; SQL statement:
create table Users(UserID int primary key, FirstName varchar(255), LastName varchar(255), e-mail varchar(255), password varchar(200), Address varchar(255), LastLginDate varchar(255), LastLoginTime varchar(200)) [50004-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4009)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3872)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5808)
	at org.h2.command.Parser.parseCreate(Parser.java:4167)
	at org.h2.command.Parser.parsePrepared(Parser.java:349)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 18:31:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "-"; SQL statement:
create table Users(UserID integer primary key, FirstName varchar(255), LastName varchar(255), e-mail varchar(255), password varchar(200), Address varchar(255), LastLoginDate varchar(255), LastLoginTime varchar(200)) [50004-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4009)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3872)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5808)
	at org.h2.command.Parser.parseCreate(Parser.java:4167)
	at org.h2.command.Parser.parsePrepared(Parser.java:349)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 18:34:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "-"; SQL statement:
create table Users(UserID int primary key, FirstName varchar(255), LastName varchar(255), e-mail varchar(255), password varchar(200), Address varchar(255), LastLginDate varchar(255), LastLoginTime varchar(200)) [50004-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4009)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3872)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5808)
	at org.h2.command.Parser.parseCreate(Parser.java:4167)
	at org.h2.command.Parser.parsePrepared(Parser.java:349)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 19:03:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERS" already exists; SQL statement:
create table Users(UserID int primary key, FirstName varchar(255), LastName varchar(255), email varchar(255), password varchar(200), Address varchar(255), LastLoginDate varchar(255), LastLoginTime varchar(200)) [42101-190]
2015-12-03 19:09:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE QUESTIONS(QUESTIONNUM INT PRIMARY KEY, QUESTION VARCHAR(1000), CATEGORY VARCHAR(100), ANSWERID INT FOREIGN[*] KEY) "; expected "(, FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
create table Questions(QuestionNum int primary key, Question varchar(1000), Category varchar(100), AnswerID int foreign key) [42001-190]
2015-12-03 19:11:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "QUESTIONS" already exists; SQL statement:
create table Questions(QuestionNum int primary key, Question varchar(1000), Category varchar(100), AnswerID int ) [42101-190]
2015-12-03 19:14:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE TESTRESULTS(TESTID INT PRIMARY KEY, USERID INT FOREIGN[*] KEY, SCORE INT, TIMETAKEN TIME) "; expected "(, FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
create table TestResults(TestID int primary key, userID int foreign key, score int, TimeTaken time) [42001-190]
2015-12-03 19:21:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "PASSWORD"; SQL statement:
ALTER TABLE Users CHANGE Password Password password(50) [50004-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4009)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3872)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5439)
	at org.h2.command.Parser.parseAlter(Parser.java:4762)
	at org.h2.command.Parser.parsePrepared(Parser.java:331)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 19:21:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "PASSWORD"; SQL statement:
ALTER TABLE Users CHANGE Password Password password(50) [50004-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4009)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3872)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5439)
	at org.h2.command.Parser.parseAlter(Parser.java:4762)
	at org.h2.command.Parser.parsePrepared(Parser.java:331)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 19:30:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ANSWERS(ANSWERID INT PRIMARY KEY, QUESTIONNUM INT FOREIGN[*] KEY, ANSWER VARCHAR(255), RIGHTANSWERCOUNT INT, WRONGANSWERCOUNT INT) "; expected "(, FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
create table answers(answerID int primary key, QuestionNum int foreign key, Answer varchar(255), RightAnswerCount int, WrongAnswerCount int) [42001-190]
2015-12-03 19:38:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "QUESTIONNUM" not found; SQL statement:
create table Answers(AnswerID int primary key, Foreign key (Questionnum) references public.Questions(Questionnum), Answer varchar(255), RightAnswerCount int, WrongAnswerCount int) [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:660)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:74)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:197)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:72)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:171)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 19:40:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "QUESTIONNUM" not found; SQL statement:
create table Answers(AnswerID int primary key, Foreign key (QUESTIONNUM ) references public.QUESTIONS (QUESTIONNUM ), Answer varchar(255), RightAnswerCount int, WrongAnswerCount int) [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:660)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:74)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:197)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:72)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:171)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 19:45:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ANSWERS" already exists; SQL statement:
create table Answers(AnswerID int primary key,QUESTIONNUM int, Foreign key (QUESTIONNUM) references public.QUESTIONS (QUESTIONNUM), Answer varchar(255), RightAnswerCount int, WrongAnswerCount int) [42101-190]
2015-12-03 19:49:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE TEST RESULTS[*](TESTID INT PRIMARY KEY, USERID INT, FOREIGN KEY(USERID) REFERENCES PUBLLIC.USERS(USERID), SCORE INT, TIMETAKEN TIME) "; SQL statement:
create table test results(TestID int primary key, UserID int, Foreign key(UserID) references publlic.users(UserID), score int, TimeTaken time) [42000-190]
2015-12-03 19:49:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Schema "PUBLLIC" not found; SQL statement:
create table testresults(TestID int primary key, UserID int, Foreign key(UserID) references publlic.users(UserID), score int, TimeTaken time) [90079-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.getSchema(Parser.java:655)
	at org.h2.command.Parser.getSchema(Parser.java:662)
	at org.h2.command.Parser.parseReferences(Parser.java:5720)
	at org.h2.command.Parser.parseAlterTableAddConstraintIf(Parser.java:5694)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5802)
	at org.h2.command.Parser.parseCreate(Parser.java:4167)
	at org.h2.command.Parser.parsePrepared(Parser.java:349)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 19:50:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "ANSWERS" already exists; SQL statement:
create table Answers(AnswerID int primary key,QUESTIONNUM int, Foreign key (QUESTIONNUM) references public.QUESTIONS (QUESTIONNUM), Answer varchar(255), RightAnswerCount int, WrongAnswerCount int) [42101-190]
2015-12-03 19:50:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "TESTRESULTS" already exists; SQL statement:
create table testresults(TestID int primary key, UserID int, Foreign key(UserID) references public.users(UserID), score int, TimeTaken time) [42101-190]
2015-12-03 19:59:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO QUESTIONS(1[*],'What is your name','general') "; expected "identifier"; SQL statement:
insert into questions(1,'What is your name','general') [42001-190]
2015-12-03 20:00:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "RIGHTANSWERS" already exists; SQL statement:
create table RightAnswers(RID int primary key, Answer varchar(500), QuestionNum int, Foreign key (QuestionNum) references public.Questions(QuestionNum), AnswerID int, Foreign key (AnswerID) references public.answers(AnswerID)) [42101-190]
2015-12-03 20:00:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "What is your name" not found; SQL statement:
insert into questions values(1,"What is your name","general") [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 20:00:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "What is your name" not found; SQL statement:
insert into questions values(1,"What is your name","general") [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-12-03 20:01:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "RIGHTANSWERS" already exists; SQL statement:
create table RightAnswers(RID int primary key, Answer varchar(500), QuestionNum int, Foreign key (QuestionNum) references public.Questions(QuestionNum), AnswerID int, Foreign key (AnswerID) references public.answers(AnswerID)) [42101-190]
